version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aya
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: aya
      MYSQL_PASSWORD: p4ssw0rd1
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ~/redis_data:/data