CREATE TABLE IF NOT EXISTS buyer (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  alamat_pengiriman VARCHAR(255) NOT NULL
);
